const Data=[
    {
     "category":"recent jobs",
     "id":"1",
     "image":"https://themesdesign.in/jobcy-react/layout/assets/images/featured-job/img-01.png",
     "experience":"1 - 2 years",
     "job":"Web Developer",
     "company":"Web Technology pvt.Ltd",
     "location":"Oakridge Lane ssRichardson",
     "price":"1000-1200/m",
     "schedule1":"Full Time",
     "schedule2":"Private",
     
    },
    {
        "category":"recent jobs",
        "id":"2",
        "image":"https://themesdesign.in/jobcy-react/layout/assets/images/featured-job/img-02.png",
        "experience":"0 - 1 years",
        "job":"Business Associate",
        "company":"Pixel Technology pvt.Ltd",
        "location":"Dodge City, Louisiana",
        "price":"800-1800/m",
        "schedule1":"Full Time",
        "schedule2":"Private",
        "schedule3":"Urgent"
       },
       {
        "category":"recent jobs",
        "id":"3",
        "image":"https://themesdesign.in/jobcy-react/layout/assets/images/featured-job/img-03.png",
        "experience":"4+ years",
        "job":"Digital Marketing Manager",
        "company":"Jobcy Technology Pvt.Ltd",
        "location":"Phoenix, Arizona",
        "price":"$1500-2400/m",
        
        "schedule4":"Part Time",
        "schedule5":"Freelancer"
       },
       {
        "category":"recent jobs",
        "id":"4",
        "image":"https://themesdesign.in/jobcy-react/layout/assets/images/featured-job/img-04.png",
        "experience":"2 - 3 years",
        "job":"Product Director",
        "company":"Creative Agency",
        "location":"Escondido, California",
        "price":"1500-2400/m",
        "schedule1":"Full Time",
        "schedule2":"Private",
       
        "schedule5":"Freelancer"
       },
    
       {
        "category":"featured jobs",
        "id":"5",
        "image":"https://themesdesign.in/jobcy-react/layout/assets/images/featured-job/img-02.png",
        "experience":"1 - 2 years",
        "job":"Web Developer",
        "company":"Web Technology pvt.Ltd",
        "location":"Oakridge Lane ssRichardson",
        "price":"1000-1200/m",
        "schedule1":"Full Time",
        "schedule2":"Private",
        "schedule3":"Urgent",
        "schedule4":"Part Time",
        "schedule5":"Freelancer"
       },
       {
           "category":"featured jobs",
           "id":"6",
           "image":"https://themesdesign.in/jobcy-react/layout/assets/images/featured-job/img-01.png",
           "experience":"0 - 1 years",
           "job":"Business Associate",
           "company":"Pixel Technology pvt.Ltd",
           "location":"Dodge City, Louisiana",
           "price":"800-1800/m",
           "schedule1":"Full Time",
           "schedule2":"Private",
           "schedule3":"Urgent",
           "schedule4":"Part Time",
           "schedule5":"Freelancer"
          },
          {
           "category":"featured jobs",
           "id":"7",
           "image":"https://themesdesign.in/jobcy-react/layout/assets/images/featured-job/img-03.png",
           "experience":"4+ years",
           "job":"Digital Marketing Manager",
           "company":"Jobcy Technology Pvt.Ltd",
           "location":"Phoenix, Arizona",
           "price":"$1500-2400/m",
           "schedule1":"Full Time",
           "schedule2":"Private",
           "schedule3":"Urgent",
           "schedule4":"Part Time",
           "schedule5":"Freelancer"
          },
          {
           "category":"featured jobs",
           "id":"8",
           "image":"https://themesdesign.in/jobcy-react/layout/assets/images/featured-job/img-04.png",
           "experience":"2 - 3 years",
           "job":"Product Director",
           "company":"Creative Agency",
           "location":"Escondido, California",
           "price":"1500-2400/m",
           "schedule1":"Full Time",
           "schedule2":"Private",
           "schedule3":"Urgent",
           "schedule4":"Part Time",
           "schedule5":"Freelancer"
          },
          {
            "category":"featured jobs",
            "id":"9",
            "image":"https://themesdesign.in/jobcy-react/layout/assets/images/featured-job/img-04.png",
            "experience":"2 - 3 years",
            "job":"Product Director",
            "company":"Creative Agency",
            "location":"Escondido, California",
            "price":"1500-2400/m",
            "schedule1":"Full Time",
            "schedule2":"Private",
            "schedule3":"Urgent",
            "schedule4":"Part Time",
            "schedule5":"Freelancer"
           },



          {
            "category":"freelancer",
            "id":"10",
            "image":"https://themesdesign.in/jobcy-react/layout/assets/images/featured-job/img-01.png",
            "experience":"1 - 2 years",
            "job":"Web Developer",
            "company":"Web Technology pvt.Ltd",
            "location":"Oakridge Lane ssRichardson",
            "price":"1000-1200/m",
            "schedule1":"Full Time",
            "schedule2":"Private",
            "schedule3":"Urgent",
            "schedule4":"Part Time",
            "schedule5":"Freelancer"
           },
           {
               "category":"freelancer",
               "id":"11",
               "image":"https://themesdesign.in/jobcy-react/layout/assets/images/featured-job/img-02.png",
               "experience":"0 - 1 years",
               "job":"Business Associate",
               "company":"Pixel Technology pvt.Ltd",
               "location":"Dodge City, Louisiana",
               "price":"800-1800/m",
               "schedule1":"Full Time",
               "schedule2":"Private",
               "schedule3":"Urgent",
               "schedule4":"Part Time",
               "schedule5":"Freelancer"
              },
              {
               "category":"freelancer",
               "id":"12",
               "image":"https://themesdesign.in/jobcy-react/layout/assets/images/featured-job/img-03.png",
               "experience":"4+ years",
               "job":"Digital Marketing Manager",
               "company":"Jobcy Technology Pvt.Ltd",
               "location":"Phoenix, Arizona",
               "price":"$1500-2400/m",
               "schedule1":"Full Time",
               "schedule2":"Private",
               "schedule3":"Urgent",
               "schedule4":"Part Time",
               "schedule5":"Freelancer"
              },
              {
               "category":"freelancer",
               "id":"13",
               "image":"https://themesdesign.in/jobcy-react/layout/assets/images/featured-job/img-04.png",
               "experience":"2 - 3 years",
               "job":"Product Director",
               "company":"Creative Agency",
               "location":"Escondido, California",
               "price":"1500-2400/m",
               "schedule1":"Full Time",
               "schedule2":"Private",
               "schedule3":"Urgent",
               "schedule4":"Part Time",
               "schedule5":"Freelancer"
              },



              {
                "category":"part time",
                "id":"14",
                "image":"https://themesdesign.in/jobcy-react/layout/assets/images/featured-job/img-01.png",
                "experience":"1 - 2 years",
                "job":"Web Developer",
                "company":"Web Technology pvt.Ltd",
                "location":"Oakridge Lane ssRichardson",
                "price":"1000-1200/m",
                "schedule1":"Full Time",
                "schedule2":"Private",
                "schedule3":"Urgent",
                "schedule4":"Part Time",
                "schedule5":"Freelancer"
               },
             
               {
                   "category":"part time",
                   "id":"15",
                   "image":"https://themesdesign.in/jobcy-react/layout/assets/images/featured-job/img-02.png",
                   "experience":"0 - 1 years",
                   "job":"Business Associate",
                   "company":"Pixel Technology pvt.Ltd",
                   "location":"Dodge City, Louisiana",
                   "price":"800-1800/m",
                   "schedule1":"Full Time",
                   "schedule2":"Private",
                   "schedule3":"Urgent",
                   "schedule4":"Part Time",
                   "schedule5":"Freelancer"
                  },
                  {
                   "category":"part time",
                   "id":"16",
                   "image":"https://themesdesign.in/jobcy-react/layout/assets/images/featured-job/img-03.png",
                   "experience":"4+ years",
                   "job":"Digital Marketing Manager",
                   "company":"Jobcy Technology Pvt.Ltd",
                   "location":"Phoenix, Arizona",
                   "price":"$1500-2400/m",
                   "schedule1":"Full Time",
                   "schedule2":"Private",
                   "schedule3":"Urgent",
                   "schedule4":"Part Time",
                   "schedule5":"Freelancer"
                  },
                  {
                   "category":"part time",
                   "id":"17",
                   "image":"https://themesdesign.in/jobcy-react/layout/assets/images/featured-job/img-04.png",
                   "experience":"2 - 3 years",
                   "job":"Product Director",
                   "company":"Creative Agency",
                   "location":"Escondido, California",
                   "price":"1500-2400/m",
                   "schedule1":"Full Time",
                   "schedule2":"Private",
                   "schedule3":"Urgent",
                   "schedule4":"Part Time",
                   "schedule5":"Freelancer"
                  },


                  {
                    "category":"full time",
                    "id":"18",
                    "image":"https://themesdesign.in/jobcy-react/layout/assets/images/featured-job/img-01.png",
                    "experience":"1 - 2 years",
                    "job":"Web Developer",
                    "company":"Web Technology pvt.Ltd",
                    "location":"Oakridge Lane ssRichardson",
                    "price":"1000-1200/m",
                    "schedule1":"Full Time",
                    "schedule2":"Private",
                    "schedule3":"Urgent",
                    "schedule4":"Part Time",
                    "schedule5":"Freelancer"
                   },
                   {
                       "category":"full time",
                       "id":"19",
                       "image":"https://themesdesign.in/jobcy-react/layout/assets/images/featured-job/img-02.png",
                       "experience":"0 - 1 years",
                       "job":"Business Associate",
                       "company":"Pixel Technology pvt.Ltd",
                       "location":"Dodge City, Louisiana",
                       "price":"800-1800/m",
                       "schedule1":"Full Time",
                       "schedule2":"Private",
                       "schedule3":"Urgent",
                       "schedule4":"Part Time",
                       "schedule5":"Freelancer"
                      },
                      {
                       "category":"full time",
                       "id":"20",
                       "image":"https://themesdesign.in/jobcy-react/layout/assets/images/featured-job/img-03.png",
                       "experience":"4+ years",
                       "job":"Digital Marketing Manager",
                       "company":"Jobcy Technology Pvt.Ltd",
                       "location":"Phoenix, Arizona",
                       "price":"$1500-2400/m",
                       "schedule1":"Full Time",
                       "schedule2":"Private",
                       "schedule3":"Urgent",
                       "schedule4":"Part Time",
                       "schedule5":"Freelancer"
                      },
                      {
                       "category":"full time",
                       "id":"21",
                       "image":"https://themesdesign.in/jobcy-react/layout/assets/images/featured-job/img-04.png",
                       "experience":"2 - 3 years",
                       "job":"Product Director",
                       "company":"Creative Agency",
                       "location":"Escondido, California",
                       "price":"1500-2400/m",
                       "schedule1":"Full Time",
                       "schedule2":"Private",
                       "schedule3":"Urgent",
                       "schedule4":"Part Time",
                       "schedule5":"Freelancer"
                      }
]
export default Data